test('Our first test', () => {
    throw new Error('something failed');
});